name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

     - uses: InstaCode/lockdown@v1
       with:
         users: abcdef-random-123456

     - run: echo hello-world
